### ISSUE TITLE
Error install 

### ISSUE THREAD

**Issue by DevShoesed** [gioboa/react-microfrontends-spotify#3]
I'have error during dependecies installation, when i do `npm run install:deps` i have this error in shell

![image](https://github.com/gioboa/react-microfrontends-spotify/assets/9318698/6fc97c0b-adc6-43ec-9373-11c8687f6b96)

I think that a module of plugin vite has renamed from `vite-module-federation-0.2.6.tgz` to `https://registry.npmjs.org/@module-federation/vite/-/vite-0.2.6.tgz`

The steps for reproduce error are there:

- clone this repository
- `cd react-microfrontends-spotify`
- `npm run install:deps`

**Comment by gioboa** [comment]
Closed by #2 #4
